//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BonusWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Bonus), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("OnTriggerEnter2DLua", get_OnTriggerEnter2DLua, set_OnTriggerEnter2DLua);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnTriggerEnter2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Bonus obj = (Bonus)o;
			System.Action<UnityEngine.Collider2D,Bonus> ret = obj.OnTriggerEnter2DLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerEnter2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnTriggerEnter2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Bonus obj = (Bonus)o;
			System.Action<UnityEngine.Collider2D,Bonus> arg0 = (System.Action<UnityEngine.Collider2D,Bonus>)ToLua.CheckDelegate<System.Action<UnityEngine.Collider2D,Bonus>>(L, 2);
			obj.OnTriggerEnter2DLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerEnter2DLua on a nil value");
		}
	}
}

